# Dockerfile development version
FROM ruby:3.2.0

# Install packages needed
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libsqlite3-0 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Default directory
ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH

# Install gems
WORKDIR $INSTALL_PATH

COPY Gemfile Gemfile.lock ./

RUN gem update --system
RUN bundle install -j $(nproc)
