version: "3.9"

x-base: &base
  build:
    context: .
    dockerfile: ./Dockerfile.dev
  stdin_open: true
  tty: true
  volumes:
    - .:/opt/app
    - bundle:/usr/local/bundle

services:
  app:
    <<: *base
    ports:
      - "3000:3000"
    command: /bin/sh -c "rm -f /opt/app/tmp/pids/server.pid && bin/rails s -p 3000 -b 0.0.0.0"

volumes:
  bundle:
