name: "Run Specs"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Rspec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup env
        run: |
          echo "PROJECT_ROOT=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Start containers
        run: docker compose -f docker-compose.yml up -d --wait

      - name: Create database
        run: docker compose -f docker-compose.yml run app rails db:setup

      - name: Run unit and request specs
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: docker compose -f docker-compose.yml run app bundle exec rspec

      - if: always()
        uses: ouzi-dev/commit-status-updater@v2
        with:
          name: "Run Specs"
          status: "${{ job.status }}"
